// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Landorphan.Abstractions.Tests.Specifications.IO.Path
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class WindowsPreparseFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "WindowsPreParse.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Windows Preparse", "\tIn order to develop a reliable Windows Path parser \r\n\tAs a member of the Landorp" +
                    "han Team\r\n\tI want to to be able to convert incoming paths into a more managable " +
                    "form", ProgrammingLanguage.CSharp, new string[] {
                        "Check-In"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Windows Preparse")))
            {
                global::Landorphan.Abstractions.Tests.Specifications.IO.Path.WindowsPreparseFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer(string path, string pre_Parsed, string notes, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Windows Preparse converter creates managable strings for the tokenizer", null, exampleTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
 testRunner.Given(string.Format("I have the following path: {0}", path), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
  testRunner.When("I preparse the path", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
  testRunner.Then(string.Format("the resulting path should read: {0}", pre_Parsed), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 0" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "(null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "(null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "Null String")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant0()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("(null)", "(null)", "Null String", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 1" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "(empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "(empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "Empty String")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant1()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("(empty)", "(empty)", "Empty String", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 2" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "C:/")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "Drive Root")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant2()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("C:`", "C:/", "Drive Root", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 3" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:`dir`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "C:/dir/file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "Drive + Dir + File")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant3()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("C:`dir`file.txt", "C:/dir/file.txt", "Drive + Dir + File", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 4" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:`dir`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "C:/dir/file.txt/")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "Drive + Dir + File + Empty")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant4()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("C:`dir`file.txt`", "C:/dir/file.txt/", "Drive + Dir + File + Empty", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 5" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:`dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "C:/dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "Drive + Dir")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant5()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("C:`dir", "C:/dir", "Drive + Dir", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 6" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:`dir`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "C:/dir/")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "Drive + Dir + Empty")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant6()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("C:`dir`", "C:/dir/", "Drive + Dir + Empty", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 7" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 7")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:.`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "C:./file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "Drive + File")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant7()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("C:.`file.txt", "C:./file.txt", "Drive + File", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 8" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:.`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "C:./file.txt/")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "Drive + File + Empty")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant8()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("C:.`file.txt`", "C:./file.txt/", "Drive + File + Empty", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 9" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 9")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "C:file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "Volume + File")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant9()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("C:file.txt", "C:file.txt", "Volume + File", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 1" +
            "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 10")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "C:file.txt/")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "Volume + File + Empty")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant10()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("C:file.txt`", "C:file.txt/", "Volume + File + Empty", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 1" +
            "1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "C:dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "Volume + Dir")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant11()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("C:dir", "C:dir", "Volume + Dir", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 1" +
            "2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 12")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:dir`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "C:dir/")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "Volume + Dir + Empty")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant12()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("C:dir`", "C:dir/", "Volume + Dir + Empty", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 1" +
            "3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 13")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:dir`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "C:dir/file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "Volume + Dir + File")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant13()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("C:dir`file.txt", "C:dir/file.txt", "Volume + Dir + File", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 1" +
            "4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 14")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:dir`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "C:dir/file.txt/")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "Volume + Dir + File + Empty")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant14()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("C:dir`file.txt`", "C:dir/file.txt/", "Volume + Dir + File + Empty", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 1" +
            "5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 15")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``server`share")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "UNC:server/share")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "UNC + Share")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant15()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("``server`share", "UNC:server/share", "UNC + Share", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 1" +
            "6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 16")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``server`share`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "UNC:server/share/")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "UNC + Share + Empty")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant16()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("``server`share`", "UNC:server/share/", "UNC + Share + Empty", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 1" +
            "7")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 17")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``server`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "UNC:server/file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "this is illegal (but not the preparser)")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant17()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("``server`file.txt", "UNC:server/file.txt", "this is illegal (but not the preparser)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 1" +
            "8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 18")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``server`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "UNC:server/file.txt/")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "again illegal")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant18()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("``server`file.txt`", "UNC:server/file.txt/", "again illegal", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 1" +
            "9")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 19")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``server`share`dir`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "UNC:server/share/dir/file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "Server + Share + Dir + File")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant19()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("``server`share`dir`file.txt", "UNC:server/share/dir/file.txt", "Server + Share + Dir + File", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 2" +
            "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 20")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``server`share`dir`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "UNC:server/share/dir/file.txt/")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "Server + Share + Dire + File + Empty")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant20()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("``server`share`dir`file.txt`", "UNC:server/share/dir/file.txt/", "Server + Share + Dire + File + Empty", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 2" +
            "1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 21")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``?`C:`dir`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "C:/dir/file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "Drive Root + Dir + File")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant21()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("``?`C:`dir`file.txt", "C:/dir/file.txt", "Drive Root + Dir + File", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 2" +
            "2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 22")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``?`C:`dir`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "C:/dir/file.txt/")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "Drive Root + Dir + File + Empty")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant22()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("``?`C:`dir`file.txt`", "C:/dir/file.txt/", "Drive Root + Dir + File + Empty", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 2" +
            "3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 23")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``?`UNC`server`share`dir`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "UNC:server/share/dir/file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "LONG: UNC + share + dir + file")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant23()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("``?`UNC`server`share`dir`file.txt", "UNC:server/share/dir/file.txt", "LONG: UNC + share + dir + file", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 2" +
            "4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 24")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``?`UNC`server`share`dir`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "UNC:server/share/dir/file.txt/")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "LONG: UNC + Share + dir + file + Empty")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant24()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("``?`UNC`server`share`dir`file.txt`", "UNC:server/share/dir/file.txt/", "LONG: UNC + Share + dir + file + Empty", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 2" +
            "5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 25")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", ".")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", ".")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "self relative")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant25()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer(".", ".", "self relative", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 2" +
            "6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 26")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", ".`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "./")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "self relative + Empty")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant26()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer(".`", "./", "self relative + Empty", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 2" +
            "7")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 27")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", ".`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "./file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "self relative + file")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant27()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer(".`file.txt", "./file.txt", "self relative + file", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 2" +
            "8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 28")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", ".`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "./file.txt/")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "self relative + file + Empty")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant28()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer(".`file.txt`", "./file.txt/", "self relative + file + Empty", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 2" +
            "9")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 29")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", ".`dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "./dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "self relative + dir")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant29()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer(".`dir", "./dir", "self relative + dir", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 3" +
            "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 30")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", ".`dir`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "./dir/")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "self relatlve + dir + Empty")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant30()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer(".`dir`", "./dir/", "self relatlve + dir + Empty", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 3" +
            "1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 31")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", ".`dir`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "./dir/file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "self reletive + dir + file")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant31()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer(".`dir`file.txt", "./dir/file.txt", "self reletive + dir + file", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 3" +
            "2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 32")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", ".`dir`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "./dir/file.txt/")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "self relatvie + dir + file + Empty")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant32()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer(".`dir`file.txt`", "./dir/file.txt/", "self relatvie + dir + file + Empty", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 3" +
            "3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 33")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "..")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "..")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "parent")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant33()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("..", "..", "parent", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 3" +
            "4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 34")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "..`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "../")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "parent + empty")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant34()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("..`", "../", "parent + empty", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 3" +
            "5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 35")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "..`dir`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "../dir/file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "parent + reletive + dir + file")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant35()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("..`dir`file.txt", "../dir/file.txt", "parent + reletive + dir + file", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 3" +
            "6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 36")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "..`dir`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "../dir/file.txt/")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "parent + relative + dir + file + empty")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant36()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("..`dir`file.txt`", "../dir/file.txt/", "parent + relative + dir + file + empty", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 3" +
            "7")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 37")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "UNC:server")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "UNC:server")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "server (illegal)")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant37()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("UNC:server", "UNC:server", "server (illegal)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 3" +
            "8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 38")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "UNC:server`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "UNC:server/")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "server + empty (illegal)")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant38()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("UNC:server`", "UNC:server/", "server + empty (illegal)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 3" +
            "9")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 39")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "UNC:server`share")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "UNC:server/share")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "server + share (legal)")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant39()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("UNC:server`share", "UNC:server/share", "server + share (legal)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 4" +
            "0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 40")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "UNC:server`share`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "UNC:server/share/")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "server + share + empty (legal)")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant40()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("UNC:server`share`", "UNC:server/share/", "server + share + empty (legal)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 4" +
            "1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 41")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "UNC:server`share`dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "UNC:server/share/dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "server + share + dir (legal)")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant41()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("UNC:server`share`dir", "UNC:server/share/dir", "server + share + dir (legal)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Preparse converter creates managable strings for the tokenizer: Variant 4" +
            "2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Preparse")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 42")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "UNC:server`share`dir`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Pre-Parsed", "UNC:server/share/dir/")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Notes", "server + share + dir + empty (legal)")]
        public virtual void WindowsPreparseConverterCreatesManagableStringsForTheTokenizer_Variant42()
        {
#line 7
this.WindowsPreparseConverterCreatesManagableStringsForTheTokenizer("UNC:server`share`dir`", "UNC:server/share/dir/", "server + share + dir + empty (legal)", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
