// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Landorphan.Abstractions.Tests.Specifications.IO.Path
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class WindowsPathSegmentsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "WindowsPathSegments.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Windows Path Segments", "\tIn order to develop a reliable Windows Path parser \r\n\tAs a member of the Landorp" +
                    "han Team\r\n\tI want to to be able to convert incoming paths into a more managable " +
                    "form", ProgrammingLanguage.CSharp, new string[] {
                        "Check-In"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Windows Path Segments")))
            {
                global::Landorphan.Abstractions.Tests.Specifications.IO.Path.WindowsPathSegmentsFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments(string path, string segment0, string segment1, string segment2, string segment3, string segment4, string segment5, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Windows Segmenter generates the following segments", null, exampleTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
 testRunner.Given(string.Format("I have the following path: {0}", path), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
  testRunner.When("I segment the Windows path", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
  testRunner.Then(string.Format("segment \'0\' should be: {0}", segment0), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
     testRunner.And(string.Format("segment \'1\' should be: {0}", segment1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
     testRunner.And(string.Format("segment \'2\' should be: {0}", segment2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
     testRunner.And(string.Format("segment \'3\' should be: {0}", segment3), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
     testRunner.And(string.Format("segment \'4\' should be: {0}", segment4), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "(null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant0()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("(null)", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "(empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant1()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("(empty)", "{E} (empty)", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{R} C:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant2()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("C:`", "{R} C:", "{E} (empty)", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:`dir`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{R} C:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant3()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("C:`dir`file.txt", "{R} C:", "{G} dir", "{G} file.txt", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:`dir`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{R} C:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant4()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("C:`dir`file.txt`", "{R} C:", "{G} dir", "{G} file.txt", "{E} (empty)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:`dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{R} C:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant5()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("C:`dir", "{R} C:", "{G} dir", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:`dir`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{R} C:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant6()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("C:`dir`", "{R} C:", "{G} dir", "{E} (empty)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 7")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 7")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:`dir``file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{R} C:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant7()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("C:`dir``file.txt", "{R} C:", "{G} dir", "{E} (empty)", "{G} file.txt", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:.`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{V} C:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{.} .")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant8()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("C:.`file.txt", "{V} C:", "{.} .", "{G} file.txt", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 9")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 9")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:.`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{V} C:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{.} .")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant9()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("C:.`file.txt`", "{V} C:", "{.} .", "{G} file.txt", "{E} (empty)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 10")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 10")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{V} C:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant10()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("C:file.txt", "{V} C:", "{G} file.txt", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{V} C:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant11()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("C:file.txt`", "{V} C:", "{G} file.txt", "{E} (empty)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 12")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 12")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{V} C:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant12()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("C:dir", "{V} C:", "{G} dir", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 13")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 13")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:dir`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{V} C:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant13()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("C:dir`", "{V} C:", "{G} dir", "{E} (empty)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 14")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 14")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:dir`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{V} C:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant14()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("C:dir`file.txt", "{V} C:", "{G} dir", "{G} file.txt", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 15")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 15")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:dir`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{V} C:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant15()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("C:dir`file.txt`", "{V} C:", "{G} dir", "{G} file.txt", "{E} (empty)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 16")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 16")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``server`share")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{U} server")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} share")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant16()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("``server`share", "{U} server", "{G} share", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 17")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 17")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``server`share`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{U} server")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} share")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant17()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("``server`share`", "{U} server", "{G} share", "{E} (empty)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 18")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 18")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``server`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{U} server")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant18()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("``server`file.txt", "{U} server", "{G} file.txt", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 19")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 19")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``server`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{U} server")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant19()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("``server`file.txt`", "{U} server", "{G} file.txt", "{E} (empty)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 20")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 20")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``server`share`dir`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{U} server")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} share")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant20()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("``server`share`dir`file.txt", "{U} server", "{G} share", "{G} dir", "{G} file.txt", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 21")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 21")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``server`share`dir`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{U} server")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} share")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant21()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("``server`share`dir`file.txt`", "{U} server", "{G} share", "{G} dir", "{G} file.txt", "{E} (empty)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 22")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 22")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``?`C:`dir`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{R} C:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant22()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("``?`C:`dir`file.txt", "{R} C:", "{G} dir", "{G} file.txt", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 23")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 23")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``?`C:`dir`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{R} C:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant23()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("``?`C:`dir`file.txt`", "{R} C:", "{G} dir", "{G} file.txt", "{E} (empty)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 24")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 24")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``?`UNC`server`share`dir`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{U} server")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} share")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant24()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("``?`UNC`server`share`dir`file.txt", "{U} server", "{G} share", "{G} dir", "{G} file.txt", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 25")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 25")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "``?`UNC`server`share`dir`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{U} server")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} share")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant25()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("``?`UNC`server`share`dir`file.txt`", "{U} server", "{G} share", "{G} dir", "{G} file.txt", "{E} (empty)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 26")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 26")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "`dir`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{/} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant26()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("`dir`file.txt`", "{E} (empty)", "{/} dir", "{G} file.txt", "{E} (empty)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 27")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 27")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", ".")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{.} .")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant27()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments(".", "{.} .", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 28")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 28")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", ".`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{.} .")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant28()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments(".`", "{.} .", "{E} (empty)", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 29")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 29")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", ".`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{.} .")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant29()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments(".`file.txt", "{.} .", "{G} file.txt", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 30")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 30")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", ".`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{.} .")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant30()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments(".`file.txt`", "{.} .", "{G} file.txt", "{E} (empty)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 31")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 31")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", ".`dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{.} .")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant31()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments(".`dir", "{.} .", "{G} dir", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 32")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 32")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", ".`dir`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{.} .")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant32()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments(".`dir`", "{.} .", "{G} dir", "{E} (empty)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 33")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 33")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", ".`dir`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{.} .")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant33()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments(".`dir`file.txt", "{.} .", "{G} dir", "{G} file.txt", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 34")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 34")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", ".`dir`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{.} .")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant34()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments(".`dir`file.txt`", "{.} .", "{G} dir", "{G} file.txt", "{E} (empty)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 35")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 35")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "..")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{..} ..")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant35()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("..", "{..} ..", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 36")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 36")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "..`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{..} ..")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant36()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("..`", "{..} ..", "{E} (empty)", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 37")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 37")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "..`dir`file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{..} ..")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant37()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("..`dir`file.txt", "{..} ..", "{G} dir", "{G} file.txt", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 38")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 38")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "..`dir`file.txt`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{..} ..")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{G} file.txt")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant38()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("..`dir`file.txt`", "{..} ..", "{G} dir", "{G} file.txt", "{E} (empty)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 39")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 39")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "CON")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{D} CON")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant39()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("CON", "{D} CON", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 40")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 40")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "C:`CON")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{R} C:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{D} CON")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant40()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("C:`CON", "{R} C:", "{D} CON", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 41")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 41")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "..`CON")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{..} ..")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{D} CON")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant41()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("..`CON", "{..} ..", "{D} CON", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 42")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 42")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "`dir`CON")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{/} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{D} CON")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant42()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("`dir`CON", "{E} (empty)", "{/} dir", "{D} CON", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 43")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 43")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "UNC:server")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{U} server")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant43()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("UNC:server", "{U} server", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 44")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 44")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "UNC:server`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{U} server")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant44()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("UNC:server`", "{U} server", "{E} (empty)", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 45")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 45")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "UNC:server`share")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{U} server")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} share")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant45()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("UNC:server`share", "{U} server", "{G} share", "{N} (null)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 46")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 46")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "UNC:server`share`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{U} server")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} share")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant46()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("UNC:server`share`", "{U} server", "{G} share", "{E} (empty)", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 47")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 47")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "UNC:server`share`dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{U} server")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} share")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant47()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("UNC:server`share`dir", "{U} server", "{G} share", "{G} dir", "{N} (null)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Windows Segmenter generates the following segments: Variant 48")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Windows Path Segments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Check-In")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 48")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Path", "UNC:server`share`dir`")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 0", "{U} server")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 1", "{G} share")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 2", "{G} dir")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 3", "{E} (empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 4", "{N} (null)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Segment 5", "{N} (null)")]
        public virtual void WindowsSegmenterGeneratesTheFollowingSegments_Variant48()
        {
#line 7
this.WindowsSegmenterGeneratesTheFollowingSegments("UNC:server`share`dir`", "{U} server", "{G} share", "{G} dir", "{E} (empty)", "{N} (null)", "{N} (null)", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
